name: "Helm Charts Updater"
author: "Vadim Gedz"
description: "A tool that will update helm charts in a given repository"
branding:
  icon: anchor
  color: gray-dark
inputs:
  github_token:
    description: "A token to commit to github repository"
    required: true
  gh_user:
    description: "The owner of helm charts git repository"
    required: true
  gh_repo:
    description: "The name of git repository with helm charts"
    required: true
  clone_path:
    description: "The path to clone the git repository"
    required: false
    default: "charts-repo"
  commit_author:
    description: "The author that will be used to commit to charts repo"
    required: false
    default: "github-actions[bot]"
  commit_email:
    description: "The email that will be used to commit to charts repo"
    required: false
    default: "github-actions[bot]@users.noreply.github.com"
  charts_path:
    description: "Path to the location of helm charts in the gh_repo"
    required: false
    default: "charts"
  chart_name:
    description: "The name of the helm chart to update"
    required: true
  app_version:
    description: "The new value for appVersion"
    required: true
  generate_docs:
    description: "Generate helm docs"
    required: false
    default: "true"
  update_readme:
    description: "Create a table with a list of charts"
    required: false
    default: "false"
  update_chart_annotations:
    description: "Add annotations to the chart reflecting the updated appVersion"
    required: false
    default: "false"
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
    INPUT_GH_USER: ${{ inputs.gh_user }}
    INPUT_GH_REPO: ${{ inputs.gh_repo }}
    INPUT_CLONE_PATH: ${{ inputs.clone_path }}
    INPUT_CHARTS_PATH: ${{ inputs.charts_path }}
    INPUT_COMMIT_AUTHOR: ${{ inputs.commit_author }}
    INPUT_COMMIT_EMAIL: ${{ inputs.commit_email }}
    INPUT_CHART_NAME: ${{ inputs.chart_name }}
    INPUT_APP_VERSION: ${{ inputs.app_version }}
    INPUT_GENERATE_DOCS: ${{ inputs.generate_docs }}
    INPUT_UPDATE_README: ${{ inputs.update_readme }}
    INPUT_UPDATE_CHART_ANNOTATIONS: ${{ inputs.update_chart_annotations }}
