name: "Helm Charts Updater"
author: "Vadim Gedz"
description: "A tool that will update helm charts in a given repository"
branding:
  icon: anchor
  color: gray-dark
inputs:
  github_token:
    description: "A token to commit to github repository"
    required: true
  gh_user:
    description: "The owner of helm charts git repository"
    required: true
  gh_repo:
    description: "The name of git repository with helm charts"
    required: true
  commit_author:
    description: "The author that will be used to commit to charts repo"
    required: false
    default: "github-actions[bot]"
  commit_email:
    description: "The email that will be used to commit to charts repo"
    required: false
    default: "github-actions[bot]@users.noreply.github.com"
  charts_path:
    description: "Path to the location of helm charts in the gh_repo"
    required: false
    default: "charts"
  chart_name:
    description: "The name of the helm chart to update"
    required: true
  app_version:
    description: "The new value for appVersion"
    required: true
  generate_docs:
    description: "Generate helm docs"
    required: false
    default: "true"
  update_readme:
    description: "Create a table with a list of charts"
    required: false
    default: "false"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.gh_user }}
    - ${{ inputs.gh_repo }}
    - ${{ inputs.charts_path }}
    - ${{ inputs.commit_author }}
    - ${{ inputs.commit_email }}
    - ${{ inputs.chart_name }}
    - ${{ inputs.app_version }}
    - ${{ inputs.generate_docs }}
    - ${{ inputs.update_readme }}
